### ISSUE TITLE
"ceph osd pool" != ceph_pool_stored in multi StorageCluster deployment

### ISSUE THREAD

**Issue by DanielOsypenko** [red-hat-storage/ocs-ci#10056]
test test_monitoring_enabled is failing on cluster with config 
```
# Config file for deploying multi StorageCluster scenario
DEPLOYMENT:
  allow_lower_instance_requirements: false
  multi_storagecluster: true
ENV_DATA:
  platform: 'vsphere'
  deployment_type: 'upi'
  worker_replicas: 3
  master_replicas: 3
  worker_num_cpus: '16'
  master_num_cpus: '4'
  master_memory: '16384'
  compute_memory: '65536'
  fio_storageutilization_min_mbps: 10.0
  storage_cluster_name: 'ocs-storagecluster'
  external_storage_cluster_name: 'ocs-external-storagecluster'
  external_storage_cluster_namespace: 'openshift-storage-extended'
REPORTING:
  polarion:
    deployment_id: 'OCS-5503'
```

https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/678/22684/1087608/1087644/log?logParams=history%3D1087644%26page.page%3D1
