### ISSUE TITLE
backing store and bucket class are in phase Rejected 

### ISSUE THREAD

**Issue by DanielOsypenko** [red-hat-storage/ocs-ci#10752]
We need to investigate on these failures. They've been caught by `test_dashboard_validation_ui` but apparently have a non-ui issue.
Issue happens on post-upgrade scenarios executed with: `OCS4-17-Downstream-OCP4-17-AWS-IPI-STS-KMS-THALES-3AZ-RHCOS-3M-3W-tier1-or-tier_after_upgrade-post-upgrade-jenkins `

screenshot 1. 
https://url.corp.redhat.com/4525e63
screenshot 2.
https://url.corp.redhat.com/521cfdf

reportportal: https://url.corp.redhat.com/d58288d

error stack trace:
```
tests/cross_functional/ui/test_validation_ui.py:90: 
...
      pytest.fail(
            "Following checks failed. 1 - Pass, 0 - Fail. \n{}".format(
                failed_checks
            )
        )
...
E           Failed: Following checks failed. 1 - Pass, 0 - Fail.
E           ['backing_store_status_ready', 'bucket_class_status']
```

**Comment by sagihirshfeld** [comment]
Looking at the YAML from the must-gather logs, it seems to be an authorization issue that's specific to STS backingstores:
```
apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  creationTimestamp: "2024-10-09T09:21:02Z"
  finalizers:
  - noobaa.io/finalizer
  generation: 1
  labels:
    app: noobaa
...
...
    manager: noobaa-operator
    operation: Update
    subresource: status
    time: "2024-10-10T08:58:39Z"
  name: noobaa-default-backing-store
  namespace: openshift-storage
...
...
spec:
  awsS3:
    awsSTSRoleARN: <CENSORED>
    region: <CENSORED>
    secret:
      name: noobaa-aws-cloud-creds-secret
      namespace: openshift-storage
    targetBucket: <CENSORED>
  type: aws-s3
status:
  conditions:
  - lastHeartbeatTime: "2024-10-10T08:58:39Z"
    lastTransitionTime: "2024-10-10T08:58:39Z"
    message: BackingStorePhaseRejected
    reason: 'Backing store mode: AUTH_FAILED'
    status: Unknown
    type: Available
```

@mashetty330 please take a look and see if it's due to an automation issue or whether it's a bug
