### ISSUE TITLE
AWS LSO - re-confirm deployment in ocs-ci matches with official deployment documentation

### ISSUE THREAD

**Issue by nehaberry** [red-hat-storage/ocs-ci#2242]
Official docs for [OCS 4.4](https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.4/html-single/deploying_openshift_container_storage/index?lb_target=preview#creating-openshift-container-storage-cluster-on-amazon-ec2_rhocs) section **1.2.4. Creating OpenShift Container Storage cluster on Amazon EC2 storage optimized - i3en.2xlarge instance type**

- [ ] 1. ocs-ci uses the storageclassname as "local-block"  but official docs have **localblock** . -  in Step 1 of Procedure

- [ ] 2. Confirm that the storagecluster CR mentioned in the doc matches(almost) with the ocs-ci StorageclusterCR we create, including the CPU and memory limits (if not already)

- [ ] 3. In official docs, as part of deployment itself, we are recommending to use "count:2" for storagedeviceSets, hence both the disks in an instance are used for OSDs. But ocs-ci currently has count:1 

**From docs**
```
  storageDeviceSets:
    - count: 2
```

- [ ] 4. If we use all the disks, add capacity test for AWS LSO should be skipped OR we need to perform node add instead (as officially documented)

Please let me know if any clarification is needed. Thanks

**Comment by ebenahar** [comment]
Once done, let's continue with https://github.com/red-hat-storage/ocs-ci/issues/2250

**Comment by petr-balogh** [comment]
@clacroix12 maybe good if you can take this up as you did all lso related stuff on I3.  Thanks

**Comment by clacroix12** [comment]
There are a couple differences still in the CR we use and the example given in the official doc. The differences being the limits/requests/memory for a few of the resources. I'm not 100% sure if these are something we want to align with so I wanted to see what you think @nehaberry.

Our CR:
```
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  manageNodes: false
  monDataDirHostPath: /var/lib/rook
  resources:
    mds:
      Limits: null
      Requests: null
    mgr:
      Limits: null
      Requests: null
    mon:
      Limits: null
      Requests: null
    noobaa-core:
      Limits: null
      Requests: null
    noobaa-db:
      Limits: null
      Requests: null
    rgw:
      Limits: null
      Requests: null
  storageDeviceSets:
  - count: 2
    dataPVCTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2300Gi
        storageClassName: localblock
        volumeMode: Block
    name: ocs-deviceset
    placement: {}
    portable: false
    replica: 3
    resources:
      Limits: null
      Requests: null
```

Example CR:
```
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  manageNodes: false
  resources:
    mds:
      limits:
        cpu: 3
      requests:
        cpu: 1
    noobaa-core:
      limits:
        cpu: 2
        memory: 8Gi
      requests:
        cpu: 1
        memory: 8Gi
    noobaa-db:
      limits:
        cpu: 2
        memory: 8Gi
      requests:
        cpu: 1
        memory: 8Gi
  monDataDirHostPath: /var/lib/rook
  storageDeviceSets:
    - count: 2
      dataPVCTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2328Gi
          storageClassName: localblock
          volumeMode: Block
      name: ocs-deviceset
      placement: {}
      portable: false
      replica: 3
      resources: {}
```
