### ISSUE TITLE
Deployment with AWS LSO fails on image fetch of OLM pod

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#2658]
When I run AWS LSO deployment `conf/deployment/aws/ipi_3az_rhcos_lso_3m_3w.yaml`, the deployment fails because container image of local storage operator pod fails to be fetched:

```
  Warning  Failed          9m12s                  kubelet, ip-10-0-151-115.us-east-2.compute.internal  Failed to pull image "registry.redhat.io/openshift4/ose-local-storage-operator@sha256:9b09d75a9c6970f4d1e65fa6f6b9af69ec462d399cccb0796963417fdff3f1de": rpc error: code = Unknown desc = Error reading manifest sha256:9b09d75a9c6970f4d1e65fa6f6b9af69ec462d399cccb0796963417fdff3f1de in registry.redhat.io/openshift4/ose-local-storage-operator: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<HTML><HEAD><TITLE>Error</TITLE></HEAD><BODY>\nAn error occurred while processing your request.<p>\nReference&#32;&#35;132&#46;b4e50b17&#46;1596788077&#46;2de55acc\n</BODY></HTML>\n"
```

**Comment by mbukatov** [comment]
The local storage operator yaml structure deployed by ocs-ci looks reasonable:
```
kind: Namespace
metadata:
  name: local-storage
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: LocalVolume.v1.local.storage.openshift.io
  name: local-storage
  namespace: local-storage
spec:
  targetNamespaces:
  - local-storage
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: local-storage-operator
  namespace: local-storage
spec:
  channel: '4.5'
  installPlanApproval: Automatic
  name: local-storage-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
```
