### ISSUE TITLE
Need to add catalog source for internal operator bundle registry image for LSO deployment over OCP 4.6

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#2908]
As OCP 4.6 is not released yet than the nightly build does not contain the LSO operator.

We see then the error like:
476 E           ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-marketplace --kubeconfig /home/cloud-user/ocp45vjp_install/auth/kubeconfig get packagemanifest local-storage-operator -n openshift-mar
477 E           Error is Error from server (NotFound): packagemanifests.packages.operators.coreos.com "local-storage-operator" not found

As I got answer that LSO already support new bundle format:
```
ART team is already generating images with new format for 4.6 -
http://dist-git.host.prod.eng.bos.redhat.com/cgit/containers/local-storage-operator-bundle/tree/?h=rhaos-4.6-rhel-7.

openshift-storage (led by Jan Safranek) are maintainers of LSO.
```

And there is also one more thread which can help here.
http://post-office.corp.redhat.com/archives/aos-devel/2020-August/msg00067.html

@shylesh or @clacroix12  can you please take this task with high priority to help Vimal to get successful deployment for interop testing?

**Comment by ebenahar** [comment]
For reference, the same is being discussed in https://chat.google.com/room/AAAAREGEba8/_DBjdmhlcj4

**Comment by clacroix12** [comment]
I was able to use the catalogsource below in order to have the LocalStorage Operator appear in the OperatorHub in the openshift UI. However, I am still having issues actually installing it once that catalogsource has been created. I'm able to successfully retrieve the channel (4.6) from the packagemanifest, however the creation of the LSO does not succeed.

CatalogSource:
```yaml
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: production-operators
  namespace: openshift-marketplace
spec:
  displayName: Production Operators
  icon:
    base64data: ""
    mediatype: ""
  image: quay.io/openshift-qe-optional-operators/ocp4-index:latest
  publisher: OpenShift QE
  sourceType: grpc
```

LSO CR:
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: local-storage
spec: {}

---

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: LocalVolume.v1.local.storage.openshift.io
  name: local-storage
  namespace: local-storage
spec:
  targetNamespaces:
  - local-storage

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: local-storage-operator
  namespace: local-storage
spec:
  channel: PLACEHOLDER
  installPlanApproval: Automatic
  name: local-storage-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
```

@petr-balogh @ebenahar Are there changes that we need to make to the installation of the LSO on OCP 4.6 now that it is an operator bundle other than adding the internal catalogsource?
