### ISSUE TITLE
AttributeError: 'CloudManager' object has no attribute

### ISSUE THREAD

**Issue by venkat-pinisetti** [red-hat-storage/ocs-ci#3016]
Seems CloudManager clients are not yet implemented for s390x platform. Hence getting below error during test execution.

**Test case:** tests/manage/mcg/test_multi_region.py::TestMultiRegion::test_multiregion_bucket_creation

**Environment:**

OCP : 4.5
OCS : 4.6
Platform : s390x

**Log:**
```
request = <SubRequest 'cloud_uls_factory' for <Function test_multiregion_bucket_creation>>, cld_mgr = <ocs_ci.ocs.resources.cloud_manager.CloudManager object at 0x3ff825adb38>

    @pytest.fixture(scope='class')
    def cloud_uls_factory(request, cld_mgr):
        """
        Create an Underlying Storage factory.
        Calling this fixture creates a new underlying storage(s).
    
        Returns:
           func: Factory method - each call to this function creates
               an Underlying Storage factory
    
        """
>       return cloud_uls_factory_implementation(request, cld_mgr)

tests/conftest.py:1877: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

request = <SubRequest 'cloud_uls_factory' for <Function test_multiregion_bucket_creation>>, cld_mgr = <ocs_ci.ocs.resources.cloud_manager.CloudManager object at 0x3ff825adb38>

    def cloud_uls_factory(request, cld_mgr):
        """
        Create an Underlying Storage factory.
        Calling this fixture creates a new underlying storage(s).
    
        Args:
            request (object): Pytest built-in fixture
            cld_mgr (CloudManager): Cloud Manager object containing all connections to clouds
    
        Returns:
            func: Factory method - each call to this function creates
                an Underlying Storage factory
    
        """
        all_created_uls = {
            'aws': set(),
            'google': set(),
            'azure': set(),
            'ibmcos': set()
        }
    
        ulsMap = {
            'aws': cld_mgr.aws_client,
>           'google': cld_mgr.google_client,
            'azure': cld_mgr.azure_client,
            # TODO: Implement - 'ibmcos': cld_mgr.ibmcos_client
        }
E       AttributeError: 'CloudManager' object has no attribute 'google_client'

ocs_ci/ocs/resources/cloud_uls.py:31: AttributeError
```
**Auth File:**
```
[root@ocsvm2 ~]# cat ocs-ci/data/auth.yaml 
quay:
  access_token: <token>
AUTH:
  AWS:
    AWS_ACCESS_KEY_ID: <ID>
    AWS_SECRET_ACCESS_KEY: <SECRET>
```

**Comment by RazTamir** [comment]
@MeridianExplorer could you please take a look at this issue?
This is blocking IBM Z and I wonder what would it take to implement the missing part on their side?

@ebenahar if you have any input on this, please share

**Comment by MeridianExplorer** [comment]
@RazTamir, @venkat-pinisetti -
This problem happened because of an incomplete `auth.yaml` file.
CloudManager is dynamically creating its attributes based on the skeleton of the `auth.yaml` file, even if it is empty.
Thus, the file needs to follow this format, even if the credentials remain empty - 
```
AUTH:
  quay:
    access_token: 

  ipmi:
  - hostname: hostname
    console: console
    username: username
    password: password

  AWS:
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY:
  GOOGLE:
    GOOGLE_APPLICATION_CREDENTIALS:
  AZURE:
    TENANT:
    CLIENT_ID:
    SECRET:
    SUBSCRIPTION_ID:
  IBMCOS:
    S3COMP: True
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    ENDPOINT:
```
