### ISSUE TITLE
OCP config installer template is not working well for 6 worker nodes cause of indention issue

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#3270]
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/14106/console
In this job we can see that config has wrong indent for replicas:
```yaml
compute:
  - name: worker
    platform:
      aws:
        type: m5.4xlarge
        zones:
          - us-east-2a
          - us-east-2b
          - us-east-2c
      replicas: 6
```

So when we have zones defined cause of indention in for loop block here:
https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/templates/ocp-deployment/install-config-aws-ipi.yaml.j2
Which we need to fix.

Working job:
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/14177/console
```yaml
compute:
  - name: worker
    platform:
      aws:
        type: m5.4xlarge
    replicas: 6
```

Here replica is intended correctly.
