### ISSUE TITLE
Add node for vmware UPI fails with KeyError: 'network_adapter'

### ISSUE THREAD

**Issue by prsurve** [red-hat-storage/ocs-ci#3295]
Logs:- http://pastebin.test.redhat.com/917197

**Comment by vavuthu** [comment]
@prsurve could you pass below config file to run-ci
```
# cat conf/ocsci/vsphere_add_nodes.yaml
---
# This configuration is used to add nodes in a cluster
ENV_DATA:
  node_count: 3
  network_adapter: "VM Network"
  add_nodes: True

```

since we already had network adapter in the initial config, I will make changes in another PR ( for teardown support )
