### ISSUE TITLE
ocs-ci is downloading openshift-client for the wrong architecture

### ISSUE THREAD

**Issue by Sarah-Kriesch** [red-hat-storage/ocs-ci#3772]
It seems, that ocs-ci does not identify the given architecture in the config.yaml. We are using the architecture s390x and the tier 4a test suite is downloading the openshift-client for x86 with tests/conftest.py. This one is not executable. It would be a nice idea to move the ocp architecture from the Upgrade part to ENV_DATA.
```
request = <SubRequest 'cluster' for <Function test_delete_noobaa_resources[noobaa_core]>>
log_cli_level = 'INFO'

    @pytest.fixture(scope="session", autouse=True)
    def cluster(request, log_cli_level):
        """
        This fixture initiates deployment for both OCP and OCS clusters.
        Specific platform deployment classes will handle the fine details
        of action
        """
        log.info(f"All logs located at {ocsci_log_path()}")
    
        teardown = config.RUN["cli_params"]["teardown"]
        deploy = config.RUN["cli_params"]["deploy"]
        if teardown or deploy:
            factory = dep_factory.DeploymentFactory()
            deployer = factory.get_deployment()
    
        # Add a finalizer to teardown the cluster after test execution is finished
        if teardown:
    
            def cluster_teardown_finalizer():
                deployer.destroy_cluster(log_cli_level)
    
            request.addfinalizer(cluster_teardown_finalizer)
            log.info("Will teardown cluster because --teardown was provided")
    
        # Download client
        force_download = (
            config.RUN["cli_params"].get("deploy")
            and config.DEPLOYMENT["force_download_client"]
        )
>       get_openshift_client(force_download=force_download)

tests/conftest.py:1098: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ocs_ci/utility/utils.py:670: in get_openshift_client
    client_version = run_cmd(f"{client_binary_path} version --client")
ocs_ci/utility/utils.py:451: in run_cmd
    completed_process = exec_cmd(cmd, secrets, timeout, ignore_error, **kwargs)
ocs_ci/utility/utils.py:490: in exec_cmd
    **kwargs,
/usr/local/lib/python3.7/subprocess.py:488: in run
    with Popen(*popenargs, **kwargs) as process:
/usr/local/lib/python3.7/subprocess.py:800: in __init__
    restore_signals, start_new_session)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <subprocess.Popen object at 0x3ff88ea9c08>, args = ['/root/ocs-ci/vbin/oc', 'version', '--client']
executable = b'/root/ocs-ci/vbin/oc', preexec_fn = None, close_fds = True, pass_fds = (), cwd = None
env = None, startupinfo = None, creationflags = 0, shell = False, p2cread = 6, p2cwrite = 7, c2pread = 8
c2pwrite = 9, errread = 10, errwrite = 11, restore_signals = True, start_new_session = False

    def _execute_child(self, args, executable, preexec_fn, close_fds,
                       pass_fds, cwd, env,
                       startupinfo, creationflags, shell,
                       p2cread, p2cwrite,
                       c2pread, c2pwrite,
                       errread, errwrite,
                       restore_signals, start_new_session):
        """Execute program (POSIX version)"""
    
        if isinstance(args, (str, bytes)):
            args = [args]
        else:
            args = list(args)
    
        if shell:
            # On Android the default shell is at '/system/bin/sh'.
            unix_shell = ('/system/bin/sh' if
                      hasattr(sys, 'getandroidapilevel') else '/bin/sh')
            args = [unix_shell, "-c"] + args
            if executable:
                args[0] = executable
    
        if executable is None:
            executable = args[0]
        orig_executable = executable
    
        # For transferring possible exec failure from child to parent.
        # Data format: "exception name:hex errno:description"
        # Pickle is not used; it is complex and involves memory allocation.
        errpipe_read, errpipe_write = os.pipe()
        # errpipe_write must not be in the standard io 0, 1, or 2 fd range.
        low_fds_to_close = []
        while errpipe_write < 3:
            low_fds_to_close.append(errpipe_write)
            errpipe_write = os.dup(errpipe_write)
        for low_fd in low_fds_to_close:
            os.close(low_fd)
        try:
            try:
                # We must avoid complex work that could involve
                # malloc or free in the child process to avoid
                # potential deadlocks, thus we do all this here.
                # and pass it to fork_exec()
    
                if env is not None:
                    env_list = []
                    for k, v in env.items():
                        k = os.fsencode(k)
                        if b'=' in k:
                            raise ValueError("illegal environment variable name")
                        env_list.append(k + b'=' + os.fsencode(v))
                else:
                    env_list = None  # Use execv instead of execve.
                executable = os.fsencode(executable)
                if os.path.dirname(executable):
                    executable_list = (executable,)
                else:
                    # This matches the behavior of os._execvpe().
                    executable_list = tuple(
                        os.path.join(os.fsencode(dir), executable)
                        for dir in os.get_exec_path(env))
                fds_to_keep = set(pass_fds)
                fds_to_keep.add(errpipe_write)
                self.pid = _posixsubprocess.fork_exec(
                        args, executable_list,
                        close_fds, tuple(sorted(map(int, fds_to_keep))),
                        cwd, env_list,
                        p2cread, p2cwrite, c2pread, c2pwrite,
                        errread, errwrite,
                        errpipe_read, errpipe_write,
                        restore_signals, start_new_session, preexec_fn)
                self._child_created = True
            finally:
                # be sure the FD is closed no matter what
                os.close(errpipe_write)
    
            # self._devnull is not always defined.
            devnull_fd = getattr(self, '_devnull', None)
            if p2cread != -1 and p2cwrite != -1 and p2cread != devnull_fd:
                os.close(p2cread)
            if c2pwrite != -1 and c2pread != -1 and c2pwrite != devnull_fd:
                os.close(c2pwrite)
            if errwrite != -1 and errread != -1 and errwrite != devnull_fd:
                os.close(errwrite)
            if devnull_fd is not None:
                os.close(devnull_fd)
            # Prevent a double close of these fds from __init__ on error.
            self._closed_child_pipe_fds = True
    
            # Wait for exec to fail or succeed; possibly raising an
            # exception (limited in size)
            errpipe_data = bytearray()
            while True:
                part = os.read(errpipe_read, 50000)
                errpipe_data += part
                if not part or len(errpipe_data) > 50000:
                    break
        finally:
            # be sure the FD is closed no matter what
            os.close(errpipe_read)
    
        if errpipe_data:
            try:
                pid, sts = os.waitpid(self.pid, 0)
                if pid == self.pid:
                    self._handle_exitstatus(sts)
                else:
                    self.returncode = sys.maxsize
            except ChildProcessError:
                pass
    
            try:
                exception_name, hex_errno, err_msg = (
                        errpipe_data.split(b':', 2))
                # The encoding here should match the encoding
                # written in by the subprocess implementations
                # like _posixsubprocess
                err_msg = err_msg.decode()
            except ValueError:
                exception_name = b'SubprocessError'
                hex_errno = b'0'
                err_msg = 'Bad exception data from child: {!r}'.format(
                              bytes(errpipe_data))
            child_exception_type = getattr(
                    builtins, exception_name.decode('ascii'),
                    SubprocessError)
            if issubclass(child_exception_type, OSError) and hex_errno:
                errno_num = int(hex_errno, 16)
                child_exec_never_called = (err_msg == "noexec")
                if child_exec_never_called:
                    err_msg = ""
                    # The error must be from chdir(cwd).
                    err_filename = cwd
                else:
                    err_filename = orig_executable
                if errno_num != 0:
                    err_msg = os.strerror(errno_num)
                    if errno_num == errno.ENOENT:
                        err_msg += ': ' + repr(err_filename)
>               raise child_exception_type(errno_num, err_msg, err_filename)
E               OSError: [Errno 8] Exec format error: '/root/ocs-ci/vbin/oc'

/usr/local/lib/python3.7/subprocess.py:1551: OSError


```
The config.yaml:
```
# in this RUN section we will keep default parameters for run of OCS-CI
RUN:
  username: 'kubeadmin'
  password_location: 'auth/kubeadmin-password'
  log_dir: "/tmp"
  run_id: null  # this will be redefined in the execution
  kubeconfig_location: 'auth/kubeconfig' # relative from cluster_dir
  cli_params: {}  # this will be filled with CLI parameters data
  # If the client version ends with .nightly, the version will be exposed
  # to the latest accepted OCP nightly build version
  **client_version: '4.6.13'**
  bin_dir: './vbin'
  #google_api_secret: '~/.ocs-ci/google_api_secret.json'
  # Following chrome params are for openshift console UI testing
  force_chrome_branch_base: "665006"
  force_chrome_branch_sha256sum: "a1ae2e0950828f991119825f62c24464ab3765aa219d150a94fb782a4c66a744"
  chrome_binary_path: "/usr/bin/chromium-browser"
  io_in_bg: False
  io_load: 30

ENV_DATA:
  cluster_name: null  # will be changed in ocscilib plugin
  storage_cluster_name: 'ocs-storagecluster'
  storage_device_sets_name: "storageDeviceSets"
  cluster_namespace: 'openshift-storage'
  local_storage_namespace: 'openshift-local-storage'
  monitoring_enabled: true
  persistent-monitoring: true
  platform: 'baremetal'
  deployment_type: 'upi'
  region: 'us-east-2'
  base_domain: 'lnxne.boe'
  master_instance_type: 'm4.xlarge'
  worker_instance_type: 'm5.4xlarge'
  master_replicas: 3
  worker_replicas: 3
  skip_ocp_deployment: false
  skip_ocs_deployment: false
  ocs_version: '4.6'

# This section is related to upgrade
UPGRADE:
  upgrade_to_latest: true
  ocp_channel: "candidate-4.6"
  ocp_upgrade_path: "quay.io/openshift-release-dev/ocp-release"
  **ocp_arch: "s390x"**
  upgrade_logging_channel: "4.6"


```

**Comment by clacroix12** [comment]
We are retrieving the openshift client from here: https://openshift-release-artifacts.apps.ci.l2s4.p1.openshiftapps.com/

We use a [combination of the client version and os type](https://github.com/red-hat-storage/ocs-ci/blob/a65be51a3f31a69ed8a17cde21c8910596c845d3/ocs_ci/utility/utils.py#L757-L758) to construct the url from which we are downloading the client tarball.

Here's an example of what's available to us once we've constructed this url: https://openshift-release-artifacts.apps.ci.l2s4.p1.openshiftapps.com/4.7.0-fc.5/

There aren't different clients in these tarballs for different architecture, only a single `oc` executable based on the os type. I'm not sure if clients built for different architecture are available but it doesn't seem like they are from where we are currently retrieving them.

**Comment by Sarah-Kriesch** [comment]
There are multiple clients for different architectures available. You can not run a binary for x86 on s390x.
We are using the openshift-clients for s390x from here: http://mirror.openshift.com/pub/openshift-v4/s390x/clients/ocp/

**Comment by petr-balogh** [comment]
@Sarah-Kriesch the thing is that we are using by default nightly builds of OCP and downloading the nightly from link what @clacroix12 described.  We are finding the latest nightly here:
https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/api/v1/releasestream/4.7.0-0.nightly/latest

and then downloading the same version of client and installer for OCP version by --ocp-version or the default one in ocs-ci which is 4.7 atm.

I don't know when nightlies for x390x platform are available for the build from latest json url I pasted above.

You also overwrite the URL template, so you can create custom config file and basically overwrite this value:
https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/framework/conf/ocp_version/ocp-4.6-ga-config.yaml#L8

You will probably also need to change also client version in your config:
https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/framework/conf/default_config.yaml#L22

To something available under your provided link like:  4.7.0-rc.0

So if I am correct you should be able to do this by creating custom config file

```yaml
RUN:
  client_version: '4.7.0-rc.0'
DEPLOYMENT:
  ocp_url_template: "https://mirror.openshift.com/pub/openshift-v4/s390x/clients/ocp/{version}/{file_name}-{os_type}-{version}.tar.gz"
```

Can you please try this and let me know if that helped and worked to you?
