### ISSUE TITLE
ocs-ci executes the tests irrespective of the skip marker which should run only on 4.6

### ISSUE THREAD

**Issue by Sravikaz** [red-hat-storage/ocs-ci#4599]
Ocs-ci executes the tests in class TestNamespace(MCGTest) during tier1, tier2 and tier3 execution, although there is a @skipif_ocs_version("!=4.6") in the below line

https://github.com/red-hat-storage/ocs-ci/blob/7bc3ffd3c93bd94ace8a3c6ee9787e71b0a265cf/tests/manage/mcg/test_namespace_rpc.py#L31

**Ocs-ci Commit:**

commit b11da4779324fdd7a7f137899debc59a0da29ca2 (HEAD -> stable, tag: stable-ocs-4.8-202107140018, origin/stable)
Merge: f81a026c 61090525
Author: Petr Balogh <petr-balogh@users.noreply.github.com>
Date:   Tue Jul 13 11:57:46 2021 +0200

    Merge pull request #4558 from prsurve/fix_add_capacity_fail

    Fix Add capacity failure for non-LSO cluster.

**config.yaml**

```
RUN:
  username: 'kubeadmin'
  password_location: 'auth/kubeadmin-password'
  log_dir: "/opt/logs"
  kubeconfig_location: 'auth/kubeconfig' # relative from cluster_dir
  bin_dir: '/usr/local/bin'
DEPLOYMENT:
  force_download_installer: false
  force_download_client: false
  ocs_csv_channel: "stable-4.8"
  local_storage: true
  skip_download_client: true
ENV_DATA:
  cluster_name: null
  storage_cluster_name: 'ocs-storagecluster'
  storage_device_sets_name: "ocs-deviceset"
  cluster_namespace: 'openshift-storage'
  ocs_version: '4.8'
  skip_ocp_deployment: true
  skip_ocs_deployment: true
  platform: 'baremetal'
  deployment_type: 'upi'
  disk_pattern: '/dev/sdb'
  local_storage_allow_rotational_disks: true
UPGRADE:
  ocp_arch: s390x
  #upgrade: true
  #upgrade_ocs_registry_image: "quay.io/rhceph-dev/ocs-registry:latest-stable-4.7.1"
REPORTING:
  default_ocs_must_gather_latest_tag: 'latest-4.8'
```

Attaching tier3 logs for reference

[tier3.zip](https://github.com/red-hat-storage/ocs-ci/files/6857108/tier3.zip)
