### ISSUE TITLE
LSO4.10 is getting deployed on OCP4.11 on IBM Power Platform

### ISSUE THREAD

**Issue by AaruniAggarwal** [red-hat-storage/ocs-ci#5916]
```
[test@nx124 logs-cron]$ oc get clusterversion
NAME      VERSION                                      AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.11.0-0.nightly-ppc64le-2022-05-14-155716   True        False         24h     Cluster version is 4.11.0-0.nightly-ppc64le-2022-05-14-155716

[test@nx124 logs-cron]$ oc get csv -n openshift-local-storage
NAME                                         DISPLAY         VERSION               REPLACES   PHASE
local-storage-operator.4.10.0-202205111015   Local Storage   4.10.0-202205111015              Succeeded

[test@nx124 logs-cron]$ oc get csv -n openshift-storage
NAME                              DISPLAY                       VERSION   REPLACES   PHASE
mcg-operator.v4.11.0              NooBaa Operator               4.11.0               Succeeded
ocs-operator.v4.11.0              OpenShift Container Storage   4.11.0               Succeeded
odf-csi-addons-operator.v4.11.0   CSI Addons                    4.11.0               Succeeded
odf-operator.v4.11.0              OpenShift Data Foundation     4.11.0               Succeeded
```

**Comment by AaruniAggarwal** [comment]
Optional-operator and Subscription used by ocs-ci : 

Optional-operator:
```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: optional-operators
  namespace: openshift-marketplace
spec:
  displayName: Optional operators
  icon:
    base64data: ''
    mediatype: ''
  image: quay.io/openshift-release-dev/ocp-release-nightly:iib-int-index-art-operators-4.11
  publisher: Red Hat
  sourceType: grpc
```

Subscription:
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: local-storage-operator
  namespace: openshift-local-storage
spec:
  channel: '4.10'
  installPlanApproval: Automatic
  name: local-storage-operator
  source: optional-operators
  sourceNamespace: openshift-marketplace
```
