### ISSUE TITLE
`test_nsfs.py` can't pull the ubi8 image in disconnected deployments 

### ISSUE THREAD

**Issue by sagihirshfeld** [red-hat-storage/ocs-ci#7006]
These tests fail with the following error message:
```
Message: ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh deployment-nsfs-interface-b208450be0dc49-7f979cbf7f-n8vms chmod -R 777 /nsfs.
Error is error: unable to upgrade connection: container not found ("ubi8")
Type: None
```

And checking the nsfs-interface pod's yaml reveals the following error:
```
containerStatuses:
  - image: registry.access.redhat.com/ubi8/ubi:8.5-214
    imageID: ""
    lastState: {}
    name: ubi8
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "registry.access.redhat.com/ubi8/ubi:8.5-214"
        reason: ImagePullBackOff
```
RP links:
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/8453/375039/375097/375099/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/8134/358552/358609/358610/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/8453/375039/375097/375098/log
https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/8134/358552/358609/358611/log
