### ISSUE TITLE
test_worker_node_restart_during_pvc_clone failed

### ISSUE THREAD

**Issue by jilju** [red-hat-storage/ocs-ci#7141]
tests/manage/pv_services/pvc_clone/test_node_restart_during_pvc_clone.py::TestNodeRestartDuringPvcClone::test_worker_node_restart_during_pvc_clone
```
 Error Details
ocs_ci.ocs.exceptions.ResourceWrongStatusException: Resource clone-pvc-test-d20cc8b8a9d045-389d9aa169 describe output: Name:          clone-pvc-test-d20cc8b8a9d045-389d9aa169
Namespace:     namespace-test-90a7860ad1d0441f8cb70dd24
StorageClass:  ocs-storagecluster-cephfs
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: openshift-storage.cephfs.csi.ceph.com
               volume.kubernetes.io/storage-provisioner: openshift-storage.cephfs.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
DataSource:
  Kind:   PersistentVolumeClaim
  Name:   pvc-test-d20cc8b8a9d045b08be456e6797af6c
Used By:  <none>
Events:
  Type     Reason                Age                     From                                                                                                                      Message
  ----     ------                ----                    ----                                                                                                                      -------
  Warning  ProvisioningFailed    9m17s                   openshift-storage.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-5cf66bc7c9-78rlt_f4162aee-b3e9-47a3-8f88-5a90d3a8e427  failed to provision volume with StorageClass "ocs-storagecluster-cephfs": rpc error: code = Aborted desc = clone from snapshot is already in progress
  Normal   Provisioning          9m16s (x2 over 9m20s)   openshift-storage.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-5cf66bc7c9-78rlt_f4162aee-b3e9-47a3-8f88-5a90d3a8e427  External provisioner is provisioning volume for claim "namespace-test-90a7860ad1d0441f8cb70dd24/clone-pvc-test-d20cc8b8a9d045-389d9aa169"
  Normal   ExternalProvisioning  3m25s (x26 over 9m20s)  persistentvolume-controller                                                                                               waiting for a volume to be created, either by external provisioner "openshift-storage.cephfs.csi.ceph.com" or manually created by system administrator
  ```
Provisioning of the volume took 23 minutes 19 seconds.
  ```
    lastTimestamp: "2023-02-10T17:56:00Z"
  message: External provisioner is provisioning volume for claim "namespace-test-dff22d6a75974155ac14626f3/clone-pvc-test-c73f9d0ac8ee4a-4299da5ec9"
  


lastTimestamp: "2023-02-10T18:19:21Z"
  message: Successfully provisioned volume pvc-04e7e2c3-f520-4e63-9ff0-76c0db33ef75
  metadata:
    creationTimestamp: "2023-02-10T18:19:21Z"
    name: clone-pvc-test-c73f9d0ac8ee4a-4299da5ec9.174289786b54edb1
  ```
