### ISSUE TITLE
Test case test_daemon_kill_during_pvc_pod_creation_deletion_and_io teardown error

### ISSUE THREAD

**Issue by jilju** [red-hat-storage/ocs-ci#8800]
The test case give below  failed due to the absence of 'rook-ceph-detect-version' pod during environment check.
tests.manage.pv_services.test_daemon_kill_during_pvc_pod_creation_deletion_and_io.TestDaemonKillDuringMultipleCreateDeleteOperations
test_daemon_kill_during_pvc_pod_creation_deletion_and_io

```
Resources removed:



'pods':

apiVersion: v1
kind: Pod
metadata:
 annotations:
   k8s.v1.cni.cncf.io/network-status: "[{\n    "name": "openshift-sdn",\n\
 \    \"interface\": \"eth0\",\n    \"ips\": [\n        \"10.129.2.60\"\n\
 \    ],\n    \"default\": true,\n    \"dns\": {}\n}]"
   openshift.io/scc: restricted-v2
   seccomp.security.alpha.kubernetes.io/pod: runtime/default
 creationTimestamp: '2023-10-10T05:29:35Z'
 deletionGracePeriodSeconds: 30
 deletionTimestamp: '2023-10-10T05:30:08Z'
 generateName: rook-ceph-detect-version-
 labels:
   app: rook-ceph-detect-version
   batch.kubernetes.io/controller-uid: aa4aa854-2244-4245-a6d8-7700ddbd7ea9
   batch.kubernetes.io/job-name: rook-ceph-detect-version
   controller-uid: aa4aa854-2244-4245-a6d8-7700ddbd7ea9
   job-name: rook-ceph-detect-version
   rook-version: v4.14.0-0.214e8dc9915769254e1de4c8238a2a9d70f75d06
 name: rook-ceph-detect-version-jz2dh
```
