### ISSUE TITLE
Update the backupschedule.yaml to have veleroTtl and useManagedServiceAccount

### ISSUE THREAD

**Issue by am-agrawa** [red-hat-storage/ocs-ci#9554]
```
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: BackupSchedule
metadata:
  name: schedule-acm
  namespace: open-cluster-management-backup
spec:
  veleroSchedule: 0 */1 * * * 
  veleroTtl: 250h
  useManagedServiceAccount: true 
  ```
