### ISSUE TITLE
AWS-UPI doesn't consider Availability zone while deployment

### ISSUE THREAD

**Issue by prsurve** [red-hat-storage/ocs-ci#991]
Param used in default_config.yaml

```
ENV_DATA:
  worker_availability_zones:
    - 'us-east-2a'
  master_availability_zones:
    - 'us-east-2a' 
```

https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/2089/

![Screenshot (13)](https://user-images.githubusercontent.com/32088367/68677772-ae841300-0582-11ea-82fe-ad49c571d7a5.png)
